### ISSUE TITLE
Invalid init schema object

### ISSUE THREAD

**Issue by jsruinedmylife** [TakNePoidet/webpack-chunks-assets-manifest#1]
When option `writeToDisk` is set to default webpack gives error:

An error occur while creating configuration ValidationError: Invalid schema object. WebpackChunksAssetsManifest has been initialized using a schema object that does not match the API schema.
 - schema.writeToDisk should be a boolean.

**Comment by TakNePoidet** [comment]
Исправлено в версии 1.0.3

**Comment by TakNePoidet** [comment]
Fixed in version 1.0.3
